Update deployment.yaml

diff --git a/templates/deployment.yaml b/templates/deployment.yaml
--- a/templates/deployment.yaml
+++ b/templates/deployment.yaml
@@ -31,7 +31,6 @@ spec:
         {{- range $key, $value := .Values.podAnnotations }}
         {{ $key }}: {{ $value | quote }}
         {{- end }}
-        {{/* This forces a restart if the configmap has changed */}}
         {{- if .Values.kibanaConfig }}
         configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
         {{- end }}
@@ -40,165 +39,158 @@ spec:
 {{- if .Values.priorityClassName }}
       priorityClassName: {{ .Values.priorityClassName }}
 {{- end }}
-      {{- if .Values.podSecurityContext }}
-            securityContext:
-      {{ toYaml .Values.podSecurityContext | indent 6 }}
-      {{- end }}
-      {{- if .Values.serviceAccount }}
+{{- if .Values.podSecurityContext }}
+      securityContext:
+{{ toYaml .Values.podSecurityContext | indent 8 }}
+{{- end }}
+{{- if .Values.serviceAccount }}
       serviceAccount: {{ .Values.serviceAccount }}
-      {{- end }}
-      {{- if .Values.hostAliases }}
-      hostAliases: {{ toYaml .Values.hostAliases | nindent 6 }}
-      {{- end }}
+{{- end }}
+{{- if .Values.hostAliases }}
+      hostAliases: {{ toYaml .Values.hostAliases | nindent 8 }}
+{{- end }}
       volumes:
         - name: kibana-tokens
           emptyDir: {}
-        {{- if .Values.elasticsearchCertificateSecret }}
+{{- if .Values.elasticsearchCertificateSecret }}
         - name: elasticsearch-certs
           secret:
             secretName: {{ .Values.elasticsearchCertificateSecret | quote }}
-        {{- end }}
-        {{- if .Values.kibanaConfig }}
+{{- end }}
+{{- if .Values.kibanaConfig }}
         - name: kibanaconfig
           configMap:
             name: {{ template "kibana.fullname" . }}-config
-        {{- end }}
-        {{- range .Values.secretMounts }}
+{{- end }}
+{{- range .Values.secretMounts }}
         - name: {{ .name }}
           secret:
-            secretName: {{ .secretName }}
-        {{- end }}
-        {{- if .Values.extraVolumes }}
-{{ toYaml .Values.extraVolumes | indent 6 }}
-        {{- end }}
-    {{- with .Values.nodeSelector }}
+            secretName: {{ .secretName | quote }}
+{{- end }}
+{{- if .Values.extraVolumes }}
+{{ toYaml .Values.extraVolumes | indent 8 }}
+{{- end }}
+{{- with .Values.nodeSelector }}
       nodeSelector:
-{{ toYaml . | indent 6 }}
-    {{- end }}
-    {{- with .Values.affinity }}
+{{ toYaml . | indent 8 }}
+{{- end }}
+{{- with .Values.affinity }}
       affinity:
-{{ toYaml . | indent 6 }}
-    {{- end }}
-    {{- with .Values.tolerations }}
+{{ toYaml . | indent 8 }}
+{{- end }}
+{{- with .Values.tolerations }}
       tolerations:
-{{ toYaml . | indent 6 }}
-    {{- end }}
-    {{- if .Values.imagePullSecrets }}
+{{ toYaml . | indent 8 }}
+{{- end }}
+{{- if .Values.imagePullSecrets }}
       imagePullSecrets:
-{{ toYaml .Values.imagePullSecrets | indent 6 }}
-    {{- end }}
+{{ toYaml .Values.imagePullSecrets | indent 8 }}
+{{- end }}
       initContainers:
-      {{- if .Values.extraInitContainers }}
-      # Currently some extra blocks accept strings
-      # to continue with backwards compatibility this is being kept
-      # whilst also allowing for yaml to be specified too.
-      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
-{{ tpl .Values.extraInitContainers . | indent 6 }}
-      {{- else }}
-{{ toYaml .Values.extraInitContainers | indent 6 }}
-      {{- end }}
-      {{- end }}
+{{- if .Values.extraInitContainers }}
+{{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
+{{ tpl .Values.extraInitContainers . | indent 8 }}
+{{- else }}
+{{ toYaml .Values.extraInitContainers | indent 8 }}
+{{- end }}
+{{- end }}
       containers:
-      - name: kibana
-        {{- if .Values.securityContext }}
-                securityContext:
-        {{ toYaml .Values.securityContext | indent 8 }}
-        {{- end }}
-        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
-        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
-        env:
-          {{- if .Values.elasticsearchURL }}
-          - name: ELASTICSEARCH_URL
-            value: "{{ .Values.elasticsearchURL }}"
-          {{- else if .Values.elasticsearchHosts }}
-          - name: ELASTICSEARCH_HOSTS
-            value: "{{ .Values.elasticsearchHosts }}"
-          {{- end }}
-          - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
-            value: "{{ template "kibana.home_dir" . }}/config/certs/{{ .Values.elasticsearchCertificateAuthoritiesFile }}"
-          - name: SERVER_HOST
-            value: "{{ .Values.serverHost }}"
-          - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
-            valueFrom:
-              secretKeyRef:
-                name: {{ template "kibana.fullname" . }}-es-token
-                key: token
-                optional: false
+        - name: kibana
+{{- if .Values.securityContext }}
+          securityContext:
+{{ toYaml .Values.securityContext | indent 12 }}
+{{- end }}
+          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
+          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
+          env:
+{{- if .Values.elasticsearchURL }}
+            - name: ELASTICSEARCH_URL
+              value: "{{ .Values.elasticsearchURL }}"
+{{- else if .Values.elasticsearchHosts }}
+            - name: ELASTICSEARCH_HOSTS
+              value: "{{ .Values.elasticsearchHosts }}"
+{{- end }}
+{{- if .Values.elasticsearchCertificateAuthoritiesFile }}
+            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
+              value: "{{ template "kibana.home_dir" . }}/config/certs/{{ .Values.elasticsearchCertificateAuthoritiesFile }}"
+{{- end }}
+            - name: SERVER_HOST
+              value: "{{ .Values.serverHost }}"
+            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
+              valueFrom:
+                secretKeyRef:
+                  name: {{ template "kibana.fullname" . }}-es-token
+                  key: token
+                  optional: false
 {{- if .Values.extraEnvs }}
-{{ toYaml .Values.extraEnvs | indent 8 }}
+{{ toYaml .Values.extraEnvs | indent 12 }}
 {{- end }}
 {{- if .Values.envFrom }}
-        envFrom:
-{{ toYaml .Values.envFrom | indent 8 }}
+          envFrom:
+{{ toYaml .Values.envFrom | indent 12 }}
 {{- end }}
-        readinessProbe:
-{{ toYaml .Values.readinessProbe | indent 8 }}
-          exec:
-            command:
-              - bash
-              - -c
-              - |
-                #!/usr/bin/env bash -e
-
-                # Disable nss cache to avoid filling dentry cache when calling curl
-                # This is required with Kibana Docker using nss < 3.52
-                export NSS_SDB_USE_CACHE=no
-
-                http () {
-                    local path="${1}"
-                    set -- -XGET -s --fail -L
-
-                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
-                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
-                    fi
-
-                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "{{ .Values.protocol }}://localhost:{{ .Values.httpPort }}${path}")
-                    if [[ "${STATUS}" -eq 200 ]]; then
-                      exit 0
-                    fi
-
-                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
-                    exit 1
-                }
-
-                http "{{ .Values.healthCheckPath }}"
-        ports:
-        - containerPort: {{ .Values.httpPort }}
+          readinessProbe:
+{{- if .Values.readinessProbe }}
+{{ toYaml .Values.readinessProbe | indent 12 }}
+{{- else }}
+            exec:
+              command:
+                - bash
+                - -c
+                - |
+                  #!/usr/bin/env bash -e
+                  export NSS_SDB_USE_CACHE=no
+                  http () {
+                      local path="${1}"
+                      set -- -XGET -s --fail -L
+                      if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
+                        set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
+                      fi
+                      STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "{{ .Values.protocol }}://localhost:{{ .Values.httpPort }}${path}")
+                      if [[ "${STATUS}" -eq 200 ]]; then
+                        exit 0
+                      fi
+                      echo "Error: Got HTTP code ${STATUS} but expected a 200"
+                      exit 1
+                  }
+                  http "{{ .Values.healthCheckPath }}"
+{{- end }}
+          ports:
+            - containerPort: {{ .Values.httpPort }}
 {{- if .Values.lifecycle }}
-        lifecycle:
-{{ toYaml .Values.lifecycle | indent 8 }}
+          lifecycle:
+{{ toYaml .Values.lifecycle | indent 12 }}
 {{- end }}
-        resources:
-{{ toYaml .Values.resources | indent 8 }}
-        volumeMounts:
-          - name: elasticsearch-certs
-            mountPath: {{ template "kibana.home_dir" . }}/config/certs
-            readOnly: true
-          - name: kibana-tokens
-            mountPath: {{ template "kibana.home_dir" . }}/config/tokens
-            readOnly: true
-          {{- range .Values.secretMounts }}
-          - name: {{ .name }}
-            mountPath: {{ .path }}
-            {{- if .subPath }}
-            subPath: {{ .subPath }}
-            {{- end }}
-          {{- end }}
-          {{- range $path, $config := .Values.kibanaConfig }}
-          - name: kibanaconfig
-            mountPath: {{ template "kibana.home_dir" . }}/config/{{ $path }}
-            subPath: {{ $path }}
-          {{- end -}}
-        {{- if .Values.extraVolumeMounts }}
-{{ toYaml .Values.extraVolumeMounts | indent 8 }}
-        {{- end }}
-      {{- if .Values.extraContainers }}
-      # Currently some extra blocks accept strings
-      # to continue with backwards compatibility this is being kept
-      # whilst also allowing for yaml to be specified too.
-      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
-{{ tpl .Values.extraContainers . | indent 6 }}
-      {{- else }}
-{{ toYaml .Values.extraContainers | indent 6 }}
-      {{- end }}
-      {{- end }}
+          resources:
+{{ toYaml .Values.resources | indent 12 }}
+          volumeMounts:
+            - name: kibana-tokens
+              mountPath: {{ template "kibana.home_dir" . }}/config/tokens
+              readOnly: true
+{{- if .Values.elasticsearchCertificateSecret }}
+            - name: elasticsearch-certs
+              mountPath: {{ template "kibana.home_dir" . }}/config/certs
+              readOnly: true
+{{- end }}
+{{- range .Values.secretMounts }}
+            - name: {{ .name }}
+              mountPath: {{ .path }}
+{{- if .subPath }}
+              subPath: {{ .subPath }}
+{{- end }}
+{{- end }}
+{{- range $path, $config := .Values.kibanaConfig }}
+            - name: kibanaconfig
+              mountPath: {{ template "kibana.home_dir" . }}/config/{{ $path }}
+              subPath: {{ $path }}
+{{- end }}
+{{- if .Values.extraVolumeMounts }}
+{{ toYaml .Values.extraVolumeMounts | indent 12 }}
+{{- end }}
+{{- if .Values.extraContainers }}
+{{- if eq "string" (printf "%T" .Values.extraContainers) }}
+{{ tpl .Values.extraContainers . | indent 10 }}
+{{- else }}
+{{ toYaml .Values.extraContainers | indent 10 }}
+{{- end }}
+{{- end }}
